In [33]:
import pandas as pd
import psycopg2
print(psycopg2.__version__)

import sqlalchemy
print(sqlalchemy.__version__)

2.9.12 (dt dec pq3 ext lo64)
2.0.22

In [2]:
data_dir="../data/edstats_data/edstats-csv-zip-32-mb-"
df1=pd.read_csv(f"{data_dir}/EdStatsCountry-Series.csv")
df2=pd.read_csv(f"{data_dir}/EdStatsCountry.csv")
df3=pd.read_csv(f"{data_dir}/EdStatsFootNote.csv")
df4=pd.read_csv(f"{data_dir}/EdStatsSeries.csv")

In [3]:
df2 = df2.rename(columns={'Country Code': 'CountryCode'})

In [5]:
df_list=[df1,df2,df3,df4,]

for a in range(len(df_list)):
    df_list[a]=df_list[a].drop(columns=[i for i in df_list[a].columns if i.startswith('Unnamed')])

In [8]:
df_list[0].head()

,CountryCode,SeriesCode,DESCRIPTION
0,ABW,SP.POP.TOTL,Data sources : United Nations World Population...
1,ABW,SP.POP.GROW,Data sources: United Nations World Population ...
2,AFG,SP.POP.GROW,Data sources: United Nations World Population ...
3,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.
4,AFG,SP.POP.TOTL,Data sources : United Nations World Population...

In [9]:
df1=df_list[0]
df2=df_list[1]
df3=df_list[2]
df4=df_list[3]

In [10]:
df1.head()

,CountryCode,SeriesCode,DESCRIPTION
0,ABW,SP.POP.TOTL,Data sources : United Nations World Population...
1,ABW,SP.POP.GROW,Data sources: United Nations World Population ...
2,AFG,SP.POP.GROW,Data sources: United Nations World Population ...
3,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.
4,AFG,SP.POP.TOTL,Data sources : United Nations World Population...

In [35]:
df1_unique=df1['DESCRIPTION'].unique().tolist()

In [36]:
df1_unique

['Data sources : United Nations World Population Prospects',
 'Data sources: United Nations World Population Prospects',
 'Estimates are based on regression.',
 'Data sources : Institute of Statistics, Eurostat',
 'Data sources : Australian Bureau of Statistics',
 'Including Other Territories comprising Jervis Bay Territory, Christmas Island and the Cocos (Keeling) Islands. ',
 'Data sources: Australian Bureau of Statistics',
 'Data sources : Eurostat',
 'Data sources : Eurostat, State Statistical Committee, United Nations World Population Prospects',
 'Data sources: Eurostat, State Statistical Committee, United Nations World Population Prospects',
 'Data sources : National Statistical Committee of the Republic of Belarus',
 'Data sources: National Statistical Committee of the Republic of Belarus',
 'Data sources : Bermuda Government Department of Statistics',
 'Data sources: Bermuda Government Department of Statistics',
 'Data sources : Statistics Canada',
 'Data sources: Statistics Canada',
 'Refers to Guernsey, and Jersey.',
 'Data sources : National Bureau of Statistics',
 'Excluding Hong Kong SAR, Macao SAR, Taiwan.',
 'Data sources: National Bureau of Statistics',
 'Data are for areas under the effective control of the Government of the Republic of Cyprus.',
 'Including Northern-Cyprus.',
 'Data sources: Eurostat, United Nations World Population Prospects. Including the French overseas departments of French Guiana, Guadeloupe, Martinique, Mayotte, and Réunion.',
 'Including the four French overseas departments (French Guyana, Guadeloupe, Martinique and Réunion)',
 'Data sources : Eurostat, United Nations World Population Prospects. Including the French overseas departments of French Guiana, Guadeloupe, Martinique, Mayotte, and Réunion.',
 'Data sources: Eurostat',
 'Data sources : GeoStats. GeoStats. Adjusted to mid-year population using geometric mean for the years where mid-year population figures are not available. Excluding Abkhazia and South Ossetia.',
 'Including Abkhazia and South Ossetia.',
 'Excludes Abkhazia and South Ossetia.',
 'Derived using ratio of age group from WPP and World Bank population.',
 'Data sources: GeoStats. GeoStats. Adjusted to mid-year population using geometric mean for the years where mid-year population figures are not available. Excluding Abkhazia and South Ossetia.',
 'Excluding Abkhazia and South Ossetia.',
 'Data sources: Statistics Greenland',
 'Data sources : Statistics Greenland',
 'Data sources: Census and Statistics Department',
 'Data sources : Census and Statistics Department',
 'Data sources: Croatian Bureau of Statistics, Council of Europe',
 'Data sources : Croatian Bureau of Statistics, Council of Europe',
 'Data sources: Central Bureau of Statistics',
 'Data sources : Central Bureau of Statistics',
 'Data sources: Ministry of Internal Affairs and Communications, Statistics Bureau; United Nations Population and Vital Statistics Report',
 'Data sources : Ministry of Internal Affairs and Communications, Statistics Bureau; United Nations Population and Vital Statistics Report',
 'Data sources : Statistical Agency of Kazakhstan, 1979 Census, 1989 Census, United Nations World Population Prospects',
 'Data sources: Statistical Agency of Kazakhstan, 1979 Census, 1989 Census, United Nations World Population Prospects',
 'Data sources : National Statistical Committee, United Nations World Population Prospects',
 'Data sources: National Statistical Committee, United Nations World Population Prospects',
 'Data sources : Korean Statistical Information Service',
 'Data sources: Korean Statistical Information Service',
 "Data sources : Registrar General's Department, Department of Census and Statistics",
 "Data sources: Registrar General's Department, Department of Census and Statistics",
 'Includes Former Spanish Sahara.',
 'Morocco only. (Excluding former Spanish Sahara)',
 "Data sources : National Bureau of Statistics. Excluding Transnistria. For 1950-94, World Bank estimates using UN World Population Prospects' growth rates of whole Moldova.",
 'Excludes Transnistria.',
 'Including Transnistria.',
 "Data sources: National Bureau of Statistics. Excluding Transnistria. For 1950-94, World Bank estimates using UN World Population Prospects 2010 Revision's growth rates of whole Moldova.",
 'Excluding Transnistria.',
 'Data sources : For 1960-1989, United Nations World Population Prospects. For 1990 onwards, 1990, 1995, 2000, 2006, 2014 censuses, and data on expatriate employment from Maldives National Bureau of Statistics. The census data are adjusted for mid-year and for foreign population.',
 'Data sources: For 1960-1989, United Nations World Population Prospects. For 1990 onwards, 1990, 1995, 2000, 2006, 2014 censuses, and data on expatriate employment from Maldives National Bureau of Statistics. The census data are adjusted for mid-year and for foreign population.',
 'Data sources : For years after 2000, Statistical Office of Montenegro. For years 1960-1999, growth rates of United Nations World Population Prospects were used to estimate backwards.',
 'Data sources : Statistics Mauritius, United Nations World Population Prospects',
 'Including Agalega and St. Brandon.',
 'Data sources: Central Statistics Office, United Nations Population and Vital Statistics Report, United Nations World Population Prospects',
 'Excluding Agalega and St. Brandon.',
 'Including Sabah and Sarawak.',
 'Data sources : Institute of Statistics and Economic Studies',
 'Data sources: Institute of Statistics and Economic Studies, 1983 Census, 1989 Census, 1996 Census',
 'Data sources: Statistics New Zealand',
 'Data sources : Statistics New Zealand',
 'Data sources : U.S. Census Bureau, 1990 Census',
 'Data sources: U.S. Census Bureau, 1990 Census',
 'Data sources : World Bank estimates based on data from Palestinian Central Bureau of Statistics, excluding E. Jerusalem.',
 'Excluding East Jerusalem.',
 'Data sources: World Bank estimates based on data from Palestinian Central Bureau of Statistics, excluding E. Jerusalem.',
 'Data sources : Russian Federation Federal State Statistics Service (its January 1st populations were adjusted to mid-year populations by using geometric mean), 1979 Census, 1989 Census.',
 'Data sources : United Nations World Population Prospects. Estimates are for Sudan excluding South Sudan.',
 'Data sources: Department of Statistics Singapore',
 'Data sources : Department of Statistics Singapore',
 'Data sources: Statistical Office of the Republic of Serbia, Eurostat, TransMONEE, Council of Europe. Excluding Kosovo for all years 1950-2011',
 'Including Kosovo.',
 'Data sources : Statistical Office of the Republic of Serbia, Eurostat, TransMONEE, Council of Europe. Note : Excluding Kosovo.',
 'Excluding Kosovo.',
 'Covers mainland Tanzania only.',
 'Including Zanzibar.',
 'Data sources : State Statistics Committee of Ukraine, United Nations World Population Prospects, Council of Europe, United Nations Population and Vital Statistics Report',
 'Data sources: State Statistics Committee of Ukraine, United Nations World Population Prospects, Council of Europe, United Nations Population and Vital Statistics Report',
 'Data sources : U.S. Census Bureau',
 'Data sources: U.S. Census Bureau',
 'Data sources : State Committee of the Republic of Uzbekistan on Statistics, United Nations World Population Prospects',
 'Based on official exchange rates.',
 'Data sources : U.S. Census Bureau, United Nations Population and Vital Statistics Report',
 'Data sources: U.S. Census Bureau, United Nations Population and Vital Statistics Report',
 'Data sources: General Statistics Office of Vietnam',
 'Data sources : General Statistics Office of Vietnam',
 "Data sources : World Bank's Kosovo coutnry office, Kosovo Agency of Statistics, U.S. Census Bureau",
 "Data sources: World Bank's Kosovo coutnry office, Kosovo Agency of Statistics, U.S. Census Bureau",
 'Data sources : Statistics South Africa, United Nations World Population Prospects']

In [20]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CountryCode  613 non-null    object
 1   SeriesCode   613 non-null    object
 2   DESCRIPTION  613 non-null    object
dtypes: object(3)
memory usage: 14.5+ KB

In [17]:
df1.duplicated(subset=['CountryCode']).sum()

402

In [18]:
df1.duplicated(subset=['CountryCode','SeriesCode']).sum()

0

In [11]:
df2.head()

,CountryCode,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,...,NaN,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   CountryCode                                        241 non-null    object
 1   Short Name                                         241 non-null    object
 2   Table Name                                         241 non-null    object
 3   Long Name                                          241 non-null    object
 4   2-alpha code                                       238 non-null    object
 5   Currency Unit                                      215 non-null    object
 6   Special Notes                                      145 non-null    object
 7   Region                                             214 non-null    object
 8   Income Group                                       214 non-null    object
 9   WB-2 code                                          240 non-null    object
 10  National accounts base year                        205 non-null    object
 11  National accounts reference year                   32 non-null     float64
 12  SNA price valuation                                197 non-null    object
 13  Lending category                                   144 non-null    object
 14  Other groups                                       58 non-null     object
 15  System of National Accounts                        215 non-null    object
 16  Alternative conversion factor                      47 non-null     object
 17  PPP survey year                                    145 non-null    object
 18  Balance of Payments Manual in use                  181 non-null    object
 19  External debt Reporting status                     124 non-null    object
 20  System of trade                                    200 non-null    object
 21  Government Accounting concept                      161 non-null    object
 22  IMF data dissemination standard                    181 non-null    object
 23  Latest population census                           213 non-null    object
 24  Latest household survey                            141 non-null    object
 25  Source of most recent Income and expenditure data  160 non-null    object
 26  Vital registration complete                        111 non-null    object
 27  Latest agricultural census                         142 non-null    object
 28  Latest industrial data                             107 non-null    float64
 29  Latest trade data                                  185 non-null    float64
 30  Latest water withdrawal data                       179 non-null    object
dtypes: float64(3), object(28)
memory usage: 58.5+ KB

In [19]:
df2.duplicated(subset=['CountryCode']).sum()

0

In [12]:
df3.head()

  CountryCode      SeriesCode    Year          DESCRIPTION
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.
2         ABW  SE.PRE.TCHR.FE  YR2000  Country estimation.
3         ABW  SE.SEC.ENRL.GC  YR2004  Country estimation.
4         ABW     SE.PRE.TCHR  YR2006  Country estimation.

In [23]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643638 entries, 0 to 643637
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CountryCode  643638 non-null  object
 1   SeriesCode   643638 non-null  object
 2   Year         643638 non-null  object
 3   DESCRIPTION  643638 non-null  object
dtypes: object(4)
memory usage: 19.6+ MB

In [39]:
df3_unique=df3['DESCRIPTION'].unique().tolist()

In [40]:
df3_unique

['Country estimation.',
 'UIS Estimation',
 'UNESCO Institute for Statistics (UIS) estimate',
 '5-year average value between 0s and 5s',
 'Percentage includes lower secondary education.',
 'Country data',
 'Country Data',
 'UNSD WPP08 revision file 2A and 3A.',
 'Not applicable',
 'Percentage includes all tertiary levels (ISCED 5-8)',
 'Estimated',
 'UIS estimation.',
 '<0.1. Plausible bound is <0.1-0.1',
 'Uncertainty bound is 127.1 - 148.2',
 'Uncertainty bound is 146.6 - 173.2',
 'Uncertainty bound is 134.1 - 157.1',
 'Uncertainty bound is 207.2 - 261.6',
 'Uncertainty bound is 60.2 - 86.1',
 'Uncertainty bound is 184.5 - 227.9',
 'Uncertainty bound is 167.8 - 201.7',
 'Uncertainty bound is 130.4 - 152.5',
 'Uncertainty bound is 240.3 - 308.5',
 'Country estimation',
 'Uncertainty bound is 212.6 - 269.3',
 'Uncertainty bound is 201.4 - 253.3',
 'Uncertainty bound is 190.1 - 236.6',
 'Uncertainty bound is 162.4 - 193.8',
 'Uncertainty bound is 123.7 - 144.2',
 'Uncertainty bound is 98.4 - 115',
 'Uncertainty bound is 56.6 - 84.7',
 'UIS estimation',
 'Uncertainty bound is 260.6 - 335.6',
 'Uncertainty bound is 229.5 - 293.2',
 'Uncertainty bound is 116.9 - 136.5',
 'Uncertainty bound is 113.4 - 132.5',
 'Uncertainty bound is 102.3 - 119.6',
 'Uncertainty bound is 90.3 - 106.6',
 'National Estimate',
 'Uncertainty bound is 255.3 - 329.5',
 'Uncertainty bound is 234.9 - 300.9',
 'Uncertainty bound is 179 - 218.9',
 'Uncertainty bound is 81.7 - 99.4',
 'Uncertainty bound is 270.4 - 347.9',
 'Uncertainty bound is 250.1 - 323.2',
 'Uncertainty bound is 156.8 - 186.4',
 'Uncertainty bound is 109.8 - 128.4',
 'Uncertainty bound is 94.4 - 110.8',
 'Uncertainty bound is 86.1 - 102.9',
 'Uncertainty bound is 77.3 - 96.3',
 'Uncertainty bound is 68.2 - 90.7',
 '<0.1. Plausible bound is <0.1-<0.1',
 'Uncertainty bound is 265.2 - 342',
 'Uncertainty bound is 245.3 - 315.6',
 'Uncertainty bound is 223.8 - 284.9',
 'Uncertainty bound is 195.8 - 245.1',
 'Uncertainty bound is 173.4 - 209.9',
 'Uncertainty bound is 72.7 - 93.4',
 'Uncertainty bound is 218.2 - 276.9',
 'Uncertainty bound is 151.6 - 179.5',
 'Uncertainty bound is 142 - 167.5',
 'Uncertainty bound is 137.7 - 162',
 'Uncertainty bound is 120.4 - 140.3',
 'Uncertainty bound is 106.1 - 124.1',
 'Uncertainty bound is 64 - 88.1',
 'WB estimate based on the UNSD WPP08 revision file 2A and 3A, and WB population.',
 'Uncertainty bound is 140.7 - 198.5',
 'Plausible bound is 1.1-1.6',
 'Uncertainty bound is 195.9 - 247.1',
 'Uncertainty bound is 50 - 151.5',
 'Uncertainty bound is 56.1 - 155.1',
 'Uncertainty bound is 200.7 - 250.2',
 'Uncertainty bound is 187.8 - 240.4',
 'Uncertainty bound is 182.6 - 235.3',
 'Uncertainty bound is 196.3 - 250',
 'Uncertainty bound is 198.6 - 249.1',
 'Uncertainty bound is 184.6 - 293.1',
 'Plausible bound is 1.5-2.2',
 'Uncertainty bound is 45 - 149.1',
 'Plausible bound is 1-1.5',
 'Plausible bound is 0.1-0.4',
 'Plausible bound is 1.4-2',
 'Plausible bound is 1-1.4',
 'Uncertainty bound is 195.4 - 252',
 'Uncertainty bound is 176.5 - 229.3',
 'Uncertainty bound is 169.5 - 222.1',
 'Uncertainty bound is 161.2 - 214.2',
 'Plausible bound is 0.2-0.6',
 'Plausible bound is 0.3-0.8',
 'Plausible bound is 1.2-1.7',
 'Plausible bound is 1.2-1.8',
 'Uncertainty bound is 181.3 - 308.1',
 'Uncertainty bound is 188 - 281.5',
 'Uncertainty bound is 192.8 - 260.1',
 'Uncertainty bound is 197.6 - 248.5',
 'Uncertainty bound is 199.4 - 249.4',
 'Uncertainty bound is 129.2 - 190.6',
 'Uncertainty bound is 73 - 161.8',
 'Uncertainty bound is 63.8 - 158.4',
 'National Estimation',
 'Plausible bound is 1.5-2.1',
 'Uncertainty bound is 117.2 - 183.5',
 'Uncertainty bound is 83.1 - 166',
 'Plausible bound is 0.2-0.5',
 'Plausible bound is 0.8-1.3',
 'Uncertainty bound is 190.1 - 273',
 'Uncertainty bound is 191.7 - 265.6',
 'Uncertainty bound is 194 - 255.8',
 'Uncertainty bound is 200.3 - 249.9',
 'Uncertainty bound is 94.3 - 171.2',
 'Plausible bound is 0.5-1',
 'Plausible bound is 0.7-1.2',
 'Plausible bound is 0.9-1.3',
 'Uncertainty bound is 198.5 - 248.6',
 'Uncertainty bound is 151.6 - 206',
 'Uncertainty bound is 105.6 - 177.2',
 'Plausible bound is 0.2-0.7',
 'Plausible bound is 0.4-0.9',
 'Plausible bound is 0.6-1.1',
 'Plausible bound is 1.3-1.9',
 'Uncertainty bound is 196.8 - 248.7',
 'Uncertainty bound is 200.1 - 250.3',
 'Uncertainty bound is 192.4 - 244.1',
 'Uncertainty bound is 41.2 - 147',
 'Uncertainty bound is 13.5 - 25.6',
 'Plausible bound is <0.1-0.1',
 'Uncertainty bound is 32.9 - 41.2',
 'Uncertainty bound is 23.6 - 31.6',
 'Uncertainty bound is 11.6 - 25.3',
 'Uncertainty bound is 12.5 - 25.3',
 'Uncertainty bound is 29.2 - 37.3',
 'Uncertainty bound is 61.6 - 163.5',
 'Uncertainty bound is 48.5 - 68',
 'Uncertainty bound is 27.8 - 35.9',
 'Uncertainty bound is 38.6 - 50',
 'Uncertainty bound is 7.3 - 24.8',
 'Uncertainty bound is 55.1 - 100.6',
 'Uncertainty bound is 26.5 - 34.6',
 'Uncertainty bound is 50.9 - 76.3',
 'Uncertainty bound is 31.8 - 39.8',
 'Uncertainty bound is 19.6 - 28.2',
 'Uncertainty bound is 43.3 - 57',
 'Uncertainty bound is 35.3 - 44.9',
 'Uncertainty bound is 30.5 - 38.5',
 'Uncertainty bound is 25 - 33.1',
 'Uncertainty bound is 9.4 - 24.9',
 'Rounds to 0.',
 'Uncertainty bound is 36.8 - 47.3',
 'Uncertainty bound is 20.9 - 29.3',
 'Uncertainty bound is 15.8 - 26.3',
 'Uncertainty bound is 8.2 - 24.7',
 'Uncertainty bound is 46 - 61.7',
 'Uncertainty bound is 22.3 - 30.4',
 'Uncertainty bound is 18.3 - 27.4',
 'Uncertainty bound is 10.1 - 25',
 'Uncertainty bound is 8.8 - 24.8',
 'Uncertainty bound is 34 - 42.9',
 'Uncertainty bound is 14.6 - 25.9',
 'Uncertainty bound is 10.8 - 25.1',
 'Magnitude nil or negligible',
 'Uncertainty bound is 59.5 - 138.4',
 'Uncertainty bound is 57.5 - 117.1',
 'Uncertainty bound is 53 - 87.1',
 'Uncertainty bound is 40.8 - 53.1',
 'Uncertainty bound is 17 - 26.7',
 'Uncertainty bound is 7.7 - 24.6',
 'Uncertainty bound is 2.8 - 4.8',
 'Uncertainty bound is 4.9 - 11.5',
 'Uncertainty bound is 5.6 - 28.5',
 'Uncertainty bound is 3 - 4.9',
 'Uncertainty bound is 2.2 - 4.7',
 'Uncertainty bound is 2.1 - 4.7',
 'Uncertainty bound is 5.6 - 21.5',
 'Uncertainty bound is 1.6 - 4.7',
 'Uncertainty bound is 2 - 4.7',
 'Uncertainty bound is 3.9 - 6.7',
 'National estimates',
 'Uncertainty bound is 5.1 - 12.9',
 'Uncertainty bound is 4.6 - 9.3',
 'Uncertainty bound is 4.4 - 8.5',
 'Uncertainty bound is 2.5 - 4.7',
 'UIS estimates',
 'Percentage includes post-secondary non-tertiary and all tertiary levels (ISCED 4-8)',
 'Uncertainty bound is 5.6 - 24.7',
 'Uncertainty bound is 3.6 - 5.9',
 'Uncertainty bound is 3.1 - 5',
 'Uncertainty bound is 2.6 - 4.7',
 'Uncertainty bound is 1.8 - 4.7',
 'Uncertainty bound is 5.5 - 18.8',
 'Uncertainty bound is 5.2 - 14.6',
 'Uncertainty bound is 4.2 - 7.7',
 'Uncertainty bound is 3.7 - 6.3',
 'Uncertainty bound is 3.4 - 5.4',
 'Uncertainty bound is 2.9 - 4.8',
 "Percentage includes bachelor's or equivalent degrees.",
 'Uncertainty bound is 4 - 7.2',
 'Uncertainty bound is 3.5 - 5.6',
 'Uncertainty bound is 2.3 - 4.7',
 'Percentage includes doctoral degree holders.',
 'Percentage includes incomplete primary education.',
 'Uncertainty bound is 5.4 - 16.6',
 'Uncertainty bound is 4.8 - 10.3',
 'Uncertainty bound is 3.2 - 5.2',
 'Uncertainty bound is 1.7 - 4.7',
 'Reference Period: 2005-2014.',
 'Reference Period: 1995-2004.',
 'Reference Period: 1985-1994.',
 'Uncertainty bound is 13.4 - 18.3',
 'Uncertainty bound is 8.1 - 8.6',
 'Internet Dial-up customers.',
 'Uncertainty bound is 10.2 - 11',
 'Population age 15-74 in the last 3 months.',
 'Uncertainty bound is 25.1 - 34',
 'Uncertainty bound is 10.7 - 12.4',
 'Uncertainty bound is 8.3 - 8.8',
 'Uncertainty bound is 18 - 24.9',
 'Uncertainty bound is 51.5 - 68.4',
 'Uncertainty bound is 84.9 - 114',
 'Uncertainty bound is 57 - 75.7',
 'Uncertainty bound is 27.7 - 37.3',
 'Uncertainty bound is 11 - 13.6',
 'Uncertainty bound is 10.8 - 13',
 'Uncertainty bound is 10.4 - 11.4',
 'Uncertainty bound is 7.8 - 8.3',
 'Uncertainty bound is 69.7 - 92.7',
 'Uncertainty bound is 41.9 - 55.7',
 'Uncertainty bound is 19.4 - 26.8',
 'Uncertainty bound is 11.9 - 15.7',
 'Uncertainty bound is 9.3 - 9.9',
 'Uncertainty bound is 8.6 - 9.1',
 'Uncertainty bound is 63 - 83.8',
 'Uncertainty bound is 12.8 - 17.4',
 'Uncertainty bound is 7.9 - 8.4',
 'Uncertainty bound is 77.1 - 102.9',
 'Uncertainty bound is 37.7 - 50.3',
 'Uncertainty bound is 21.1 - 28.8',
 'Uncertainty bound is 16.8 - 23.3',
 'Uncertainty bound is 15.8 - 21.9',
 'Uncertainty bound is 14.9 - 20.6',
 'Uncertainty bound is 14.1 - 19.4',
 'Uncertainty bound is 12.3 - 16.5',
 'Uncertainty bound is 11.5 - 15',
 'Uncertainty bound is 7.4 - 8.3',
 'Refers to the total population.',
 'Break in comparability. Population age 15-74 in the last 3 months (exc. population living in working camps).',
 'Uncertainty bound is 46.4 - 61.8',
 'Uncertainty bound is 9.8 - 10.4',
 'Uncertainty bound is 9.5 - 10.1',
 'Uncertainty bound is 8.8 - 9.3',
 'Uncertainty bound is 34 - 45.4',
 'Uncertainty bound is 30.6 - 41.1',
 'Uncertainty bound is 23 - 31.2',
 'Uncertainty bound is 11.2 - 14.3',
 'Uncertainty bound is 10.6 - 11.8',
 'Uncertainty bound is 10 - 10.6',
 'Uncertainty bound is 9 - 9.6',
 'Uncertainty bound is 7.6 - 8.3',
 'Uncertainty bound is 7.1 - 8.4',
 'Uncertainty bound is 65.2 - 72.3',
 'Uncertainty bound is 30.5 - 31.7',
 'Uncertainty bound is 68.5 - 74.4',
 'Uncertainty bound is 34.1 - 35.4',
 'Uncertainty bound is 17.8 - 18.5',
 'Uncertainty bound is 21.6 - 22.5',
 'Uncertainty bound is 16.3 - 16.9',
 'Uncertainty bound is 32.1 - 33.3',
 'Uncertainty bound is 50.5 - 52.8',
 'Uncertainty bound is 15.1 - 15.7',
 'Uncertainty bound is 28.3 - 29.3',
 'Uncertainty bound is 24.9 - 25.9',
 'Uncertainty bound is 27.8 - 28.9',
 'Uncertainty bound is 15.8 - 16.4',
 'Plausible bound is 0.3-0.3',
 'Uncertainty bound is 27.1 - 28.1',
 'Uncertainty bound is 12.5 - 13',
 'Percentage includes post-secondary non-tertiary education.',
 'The procedure for identifying International Benchmarks changed from the PIRLS 2001 method of using percentiles to a method based on scores that do not change from PIRLS cycle to cycle. In PIRLS 2001, the Intermediate Benchmark was called the "Median Benchmark" (50th percentile score or median), which corresponded to a scale score of 510. The 2001 data in this database were recalculated based on a 475 Intermediate Benchmark score and are different than the data found in the 2001 PIRLS report.',
 'The procedure for identifying International Benchmarks changed from the PIRLS 2001 method of using percentiles to a method based on scores that do not change from PIRLS cycle to cycle. In PIRLS 2001, the Low Benchmark was called the "Lower Quarter Benchmark" (25th percentile score), which corresponded to a scale score of 435. The 2001 data in this database were recalculated based on a 400 Low Benchmark score and are different than the data found in the 2001 PIRLS report.',
 'Uncertainty bound is 28.6 - 29.7',
 'Plausible bound is 0.4-0.4',
 'Uncertainty bound is 63.3 - 70',
 'Uncertainty bound is 42.7 - 44.3',
 'Uncertainty bound is 29.4 - 30.5',
 'Uncertainty bound is 22.7 - 23.6',
 'Uncertainty bound is 10.6 - 11.7',
 'Coverage is too small to ensure comparability. For more information, see PISA 2015 Results Volume 1, Annex A4.',
 'Uncertainty bound is 36.5 - 37.9',
 'Uncertainty bound is 18.4 - 19.1',
 'Uncertainty bound is 15.5 - 16.1',
 'Population aged 10+. Estimated based on survey results for urban population.',
 'Uncertainty bound is 58.1 - 62.5',
 'Uncertainty bound is 19.8 - 20.5',
 'Uncertainty bound is 14.7 - 15.3',
 'Uncertainty bound is 11.9 - 12.4',
 'Uncertainty bound is 11.2 - 12',
 'The procedure for identifying International Benchmarks changed from the PIRLS 2001 method of using percentiles to a method based on scores that do not change from PIRLS cycle to cycle. In PIRLS 2001, the High Benchmark was called the "Upper Quarter Benchmark" or 75th percentile score, which corresponded to a scale score of 570. The 2001 data in this database were recalculated based on a 550 High Benchmark score and are different than the data found in the 2001 PIRLS report.',
 'The World Bank systematically assesses the appropriateness of official exchange rates as conversion factors. An alternative conversion factor is used when the official exchange rate is judged to diverge by an exceptionally large margin from the rate effectively applied to domestic transactions of foreign currencies and traded products. In the case of Argentina, the World Bank has found that during 2012-2015 there were two exchange rates (official and parallel) and parallel exchange rate (blue chip swap rate) was used in around 20% of the transactions. Based on this information an alternative conversion factor has been calculated using a weighted average method for this period.',
 'Actual base salaries.',
 'Uncertainty bound is 69.5 - 75.3',
 'Uncertainty bound is 67 - 73.6',
 'Uncertainty bound is 46.4 - 48.3',
 'Uncertainty bound is 17.3 - 17.9',
 'The procedure for identifying International Benchmarks changed from the PIRLS 2001 method of using percentiles to a method based on scores that do not change from PIRLS cycle to cycle. In PIRLS 2001, the Advanced benchmark was called the "Top 10% Benchmark" (90th percentile score), which corresponded to a scale score of 615. The 2001 data in this database were recalculated based on a 625 Advanced Benchmark score and are different than the data found in the 2001 PIRLS report.',
 'Plausible bound is 0.3-0.4',
 'Uncertainty bound is 61 - 66.6',
 'Uncertainty bound is 39.3 - 40.8',
 'Uncertainty bound is 28.5 - 29.6',
 '1997 scores are not comparable with 2006 scores. 1997 scores were calculated on a scale with a mean of 250 points and a standard deviation of 50 points. 2006 scores were calculated on a scale with a mean of 500 and a standard deviation of 100 points.',
 'Plausible bound is 0.2-0.3',
 'Uncertainty bound is 54.5 - 57.7',
 'Uncertainty bound is 28.8 - 29.9',
 'Uncertainty bound is 26.1 - 27.1',
 'Uncertainty bound is 23.8 - 24.7',
 'Uncertainty bound is 20.7 - 21.5',
 'Uncertainty bound is 19 - 19.8',
 'Uncertainty bound is 16.7 - 17.4',
 'Uncertainty bound is 14.2 - 14.8',
 'Uncertainty bound is 13.6 - 14.2',
 'Uncertainty bound is 13.1 - 13.6',
 'Uncertainty bound is 27.1 - 33.2',
 'Uncertainty bound is 33.4 - 40.3',
 'Uncertainty bound is 25.7 - 31.7',
 'Uncertainty bound is 20.6 - 26.3',
 'Uncertainty bound is 13.5 - 20',
 'Uncertainty bound is 24.3 - 30.2',
 'Uncertainty bound is 37 - 44.7',
 'Uncertainty bound is 69.6 - 94.1',
 'Uncertainty bound is 45.2 - 54.6',
 'Uncertainty bound is 65.8 - 85',
 'Uncertainty bound is 63.8 - 80.9',
 'Uncertainty bound is 41 - 49.5',
 'Uncertainty bound is 15.4 - 21.4',
 'Uncertainty bound is 14.5 - 20.6',
 'Uncertainty bound is 12.7 - 19.3',
 'Uncertainty bound is 11 - 18.2',
 'All population.',
 'Uncertainty bound is 61.8 - 77.2',
 'Uncertainty bound is 59.7 - 73.9',
 'Uncertainty bound is 23 - 28.8',
 'Uncertainty bound is 11.8 - 18.8',
 'Plausible bound is <0.1-0.2',
 'Uncertainty bound is 72.8 - 105.1',
 'Uncertainty bound is 57.7 - 70.8',
 'Uncertainty bound is 55.6 - 67.7',
 'Uncertainty bound is 53.5 - 64.8',
 'Uncertainty bound is 47.3 - 57.1',
 'Uncertainty bound is 28.6 - 34.8',
 'Uncertainty bound is 19.4 - 25.1',
 'Uncertainty bound is 30.1 - 36.5',
 'Uncertainty bound is 21.8 - 27.5',
 'Uncertainty bound is 17.3 - 23',
 'Uncertainty bound is 10.3 - 17.8',
 'Plausible bound is 0.1-0.2',
 'Uncertainty bound is 74.2 - 89.6',
 'Uncertainty bound is 43.1 - 52',
 'Uncertainty bound is 39 - 47',
 'Uncertainty bound is 16.3 - 22.2',
 'Uncertainty bound is 71.3 - 99.4',
 'Uncertainty bound is 67.7 - 89.4',
 'Uncertainty bound is 51.5 - 62.2',
 'Uncertainty bound is 35.1 - 42.5',
 'Uncertainty bound is 31.7 - 38.4',
 'Uncertainty bound is 18.4 - 24',
 'Uncertainty bound is 18.2 - 29.2',
 'Uncertainty bound is 6.3 - 11.4',
 'Uncertainty bound is 9.6 - 12.5',
 'Uncertainty bound is 18.6 - 36.2',
 'Uncertainty bound is 18.3 - 66.5',
 'Uncertainty bound is 13.4 - 16.6',
 'Population age 5+. Census.',
 'Uncertainty bound is 16.4 - 20.6',
 'Uncertainty bound is 15.6 - 19.3',
 'Uncertainty bound is 8.4 - 11.8',
 'Uncertainty bound is 8 - 11.7',
 'Uncertainty bound is 18.4 - 58.4',
 'Uncertainty bound is 18.4 - 32.5',
 'Uncertainty bound is 14.9 - 18.3',
 'Uncertainty bound is 14.1 - 17.3',
 'Uncertainty bound is 12.2 - 15.3',
 'Uncertainty bound is 11.2 - 14.1',
 'Uncertainty bound is 10.8 - 13.6',
 'Uncertainty bound is 10.4 - 13.2',
 'Uncertainty bound is 7.1 - 11.5',
 'Uncertainty bound is 6.7 - 11.5',
 'Uncertainty bound is 18.6 - 40.7',
 'Uncertainty bound is 12.7 - 15.9',
 'Uncertainty bound is 11.7 - 14.7',
 'Uncertainty bound is 9.2 - 12.2',
 'Uncertainty bound is 17.9 - 26.5',
 'Uncertainty bound is 17.5 - 24.2',
 'Uncertainty bound is 10 - 12.8',
 'Uncertainty bound is 8.8 - 12',
 'Uncertainty bound is 18.6 - 51.7',
 'Uncertainty bound is 18.7 - 45.8',
 'Uncertainty bound is 17 - 22.2',
 'Uncertainty bound is 7.5 - 11.6',
 'Including Christmas Island, Cocos (Keeling) Islands, and Norfolk Island.',
 'Uncertainty bound is 6.3 - 6.6',
 'Uncertainty bound is 13.4 - 13.9',
 'Uncertainty bound is 11.4 - 11.8',
 'Uncertainty bound is 8 - 8.3',
 'Uncertainty bound is 4.1 - 4.2',
 'Uncertainty bound is 4.5 - 4.7',
 'Uncertainty bound is 5.1 - 5.3',
 'Uncertainty bound is 7.2 - 7.5',
 'Uncertainty bound is 21 - 21.9',
 'Uncertainty bound is 5.6 - 5.8',
 'Uncertainty bound is 5.9 - 6.1',
 'Percentage includes no schooling and incomplete primary education. Data for population 25 to 64 years.',
 'Individuals aged 15 years and over',
 'Uncertainty bound is 20.6 - 21.4',
 'Uncertainty bound is 11.1 - 11.5',
 'Uncertainty bound is 7.6 - 7.8',
 'Uncertainty bound is 6.2 - 6.4',
 'Uncertainty bound is 6 - 6.2',
 'Uncertainty bound is 4.9 - 5.1',
 'Data for population 25 to 64 years.',
 'Statutory salaries do not include the the part of social security contributions and pension-scheme contributions paid by the employees.',
 'Excludes the social security contributions and pension-scheme contributions paid by the employees.',
 'Plausible bound is 0.1-0.1',
 'Uncertainty bound is 19.1 - 19.8',
 'Uncertainty bound is 15.9 - 16.5',
 'Uncertainty bound is 6.5 - 6.7',
 'Uncertainty bound is 5.3 - 5.5',
 'Preliminary.',
 'Data for population 25 to 64 years',
 'Percentage includes incomplete primary education. Data for population 25 to 64 years.',
 'Population age 15+.',
 'Uncertainty bound is 18.1 - 18.8',
 'Uncertainty bound is 17 - 17.6',
 'Uncertainty bound is 12.8 - 13.3',
 'Uncertainty bound is 6.6 - 6.9',
 'Uncertainty bound is 6.1 - 6.3',
 'Uncertainty bound is 4.7 - 4.9',
 'Statutory salaries do not include the part of social security contributions and pension-scheme contributions paid by the employees.',
 'Uncertainty bound is 11.6 - 12.1',
 'Uncertainty bound is 10.8 - 11.2',
 'Uncertainty bound is 9.5 - 9.9',
 'Uncertainty bound is 6.9 - 7.2',
 'Uncertainty bound is 5.7 - 5.9',
 'Uncertainty bound is 3.7 - 4',
 'Magnitude nil or negligible; Percentage includes incomplete primary education. Data for population 25 to 64 years.',
 'Uncertainty bound is 9 - 9.4',
 'Uncertainty bound is 8.5 - 8.8',
 'Uncertainty bound is 5.8 - 6',
 'Uncertainty bound is 4.3 - 4.4',
 'Uncertainty bound is 3.9 - 4.1',
 'Percentage includes all tertiary levels (ISCED 5-8). Data for population 25 to 64 years.',
 'Uncertainty bound is 19.9 - 20.7',
 'Uncertainty bound is 15 - 15.5',
 'Uncertainty bound is 14.1 - 14.6',
 'Uncertainty bound is 12.3 - 12.8',
 'Uncertainty bound is 10.4 - 10.8',
 'Uncertainty bound is 10 - 10.4',
 'Uncertainty bound is 5.5 - 5.7',
 'Uncertainty bound is 3.5 - 3.9',
 'Not applicable. Data for population 25 to 64 years.',
 'Magnitude nil or negligible. Data for population 25 to 64 years.',

In [24]:
df3.duplicated(subset=['CountryCode']).sum()

643399

In [25]:
df3.duplicated(subset=['SeriesCode']).sum()

642080

In [26]:
df3.duplicated(subset=['Year']).sum()

643582

In [27]:
df3.duplicated(subset=['CountryCode','SeriesCode']).sum()

570652

In [28]:
df3.duplicated(subset=['CountryCode','SeriesCode','Year']).sum()

0

In [13]:
df4.head()

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
0,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...,Percentage of female population age 15-19 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN
1,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...,Percentage of population age 15-19 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN
2,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...,Percentage of female population age 15+ with n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN
3,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...,Percentage of population age 15+ with no educa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN
4,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...,Percentage of female population age 20-24 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SeriesCode                           3665 non-null   object
 1   Topic                                3665 non-null   object
 2   Indicator Name                       3665 non-null   object
 3   Short definition                     2156 non-null   object
 4   Long definition                      3665 non-null   object
 5   Unit of measure                      0 non-null      float64
 6   Periodicity                          99 non-null     object
 7   Base Period                          314 non-null    object
 8   Other notes                          552 non-null    object
 9   Aggregation method                   47 non-null     object
 10  Limitations and exceptions           14 non-null     object
 11  Notes from original source           0 non-null      float64
 12  General comments                     14 non-null     object
 13  Source                               3665 non-null   object
 14  Statistical concept and methodology  23 non-null     object
 15  Development relevance                3 non-null      object
 16  Related source links                 215 non-null    object
 17  Other web links                      0 non-null      float64
 18  Related indicators                   0 non-null      float64
 19  License Type                         0 non-null      float64
dtypes: float64(5), object(15)
memory usage: 572.8+ KB

In [30]:
df4 = df4.rename(columns={'Series Code': 'SeriesCode'})

In [32]:
df4.duplicated(subset=['SeriesCode']).sum()

0

In [34]:
from sqlalchemy import create_engine

# format: postgresql://username:password@host:port/database_name
engine = create_engine('postgresql://superuser:password@database:5432/analysis')

In [37]:
df1.to_sql(
    name='edstats_footnotes',
    con=engine,
    if_exists='fail',
    index=False)

613

In [41]:
df2.to_sql(
    name='edstats_country_info',
    con=engine,
    if_exists='fail',
    index=False)

241

In [42]:
df3.to_sql(
    name='edstats_uncertainty',
    con=engine,
    if_exists='fail',
    index=False)

638

In [43]:
df4.to_sql(
    name='edstats_code_info',
    con=engine,
    if_exists='fail',
    index=False)

665